services:
    mysql:
        image: mysql:8.0.17
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=12345
          - MYSQL_DATABASE=database
        volumes:
          - ./mysql-data:/var/lib/mysql
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
          - "3306:3306"